### ISSUE TITLE
package model cannot be found (chapter 4, 5)

### ISSUE THREAD

**Issue by ricardoseb** [PacktPublishing/Modern-API-Development-with-Spring-and-Spring-Boot#1]
I'm looking for the package as it is used with the classes in the hateoas package, but they are not added to the repository. Is it possible to upload them to verify the classes in those chapters?

**Comment by shubham763** [comment]
Hi @ricardoseb

All the sources are present in the repository. Some of them are generated files that were not added to the repository as it was a generated file. I'm not sure which package you need, please let us know if you're asking for any specific package.

Regards,
Shubham
