### ISSUE TITLE
Is this new version of code's repo ?

### ISSUE THREAD

**Issue by javadance** [PacktPublishing/Modern-API-Development-with-Spring-and-Spring-Boot#10]
I found this (https://github.com/PacktPublishing/Modern-API-Development-with-Spring-6-and-Spring-Boot-3) repo. Is this new version of code? I'm finishing this book in Korean and about to print this. I would like to upgrade source code to latest version.

Please let me know.

**Comment by sharmasourabh** [comment]
Hi @javadance 
This code belongs to new edition of this book which is in progress. Therefore, I think, [this](https://github.com/PacktPublishing/Modern-API-Development-with-Spring-and-Spring-Boot) repo should only be used for current edition.

**Comment by javadance** [comment]
@sharmasourabh Yeah, I know this repo is for current book which I'm finishing translation in Korean. But because of Korean translation had been slightly relayed, I think I have to upgrade the source version to Spring 6&Spring Boot3 compatible for Korean readers. Would you walk me through for upgrading your source code??

**Comment by javadance** [comment]
@sharmasourabh And I sent DM to you in Twitter. But it seems like you don't use it anymore.
