### ISSUE TITLE
Could not find method javplugins()

### ISSUE THREAD

**Issue by hernihub** [PacktPublishing/Modern-API-Development-with-Spring-and-Spring-Boot#11]
Hi.
I just bought the book and I'm kinda stuck in Chapter04, as clean and build is throwing the error:

`Could not find method javplugins() for arguments [build_c8ibzmuhawfr1rzcd03uf9wqr$_run_closure1@23fba7f6] on root project 'Chapter04' of type org.gradle.api.Project.
`
When I hover the javplugins declaration in build.gradle file, it says: `No candidates found for method call javplugins.
  Chapter04`

I tried reloading all gradle projects and invalidate cache and restart IntelliJ. I just cloned the repo, open Chapter04 in InteliiJ and typed gradlew clean build in the terminal. Running JDK 15, Win 11.

Any help will be greatly appreciated!

**Comment by hernihub** [comment]
It was a typo: 'jav' in plugins block.

**Comment by sharmasourabh** [comment]
Hi,
It works without any issue for me.
Can you please try building from terminal and share the full logs here, including the output of `java --version`?

**Comment by sharmasourabh** [comment]
I hope it is working now.
> It was a typo: 'jav' in plugins block.
