### ISSUE TITLE
Another typo ?

### ISSUE THREAD

**Issue by javadance** [PacktPublishing/Modern-API-Development-with-Spring-and-Spring-Boot#8]
Sorry to bother.
In 269 page, there is sentence such as "The login operation sets the access token, refresh token, user ID, and username in the responseToken key of the local storage by using the state arguments passed by the App component."   I think that 'responseToken' should be 'tokenResponse', isn't it?

**Comment by sharmasourabh** [comment]
Thanks for notifying.

Yes, it is typo. It should be `tokenResponse`

**Comment by JosephA-packt** [comment]
I hope your query has been addressed @javadance. Hence I would be closing this issue. Thanks for pointing us out that errata.
